name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: [self-hosted, dev]

    steps:
    - uses: actions/checkout@v3
    - name: Checkout Source code
      id: checkout
      run: echo "test"

    - name: set lower case repository name
      id: lc-repository
      run: |
           echo "REPOSITORY_LC=${REPOSITORY,,}" >>${GITHUB_ENV}
      env:
         REPOSITORY: '${{ github.repository }}'

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: 099532347933.dkr.ecr.us-east-2.amazonaws.com
        GIT_BRANCH: ${{ github.ref_name }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        aws ecr get-login-password --region us-east-2 | sudo docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }} 
        aws ecr create-repository --repository-name ${{ env.REPOSITORY_LC }} || true
        sudo docker build -t ${{ env.ECR_REGISTRY }}/${{ env.REPOSITORY_LC }}:master .
        sudo docker push ${{ env.ECR_REGISTRY }}/${{ env.REPOSITORY_LC }}:master
        sudo docker system prune --force --filter "until=24h"
